### ISSUE TITLE
Not all characteristics are found 

### ISSUE THREAD

**Issue by simo792** [mhamilt/maxmsp-ble#20]
I find that max-ble doesn't successfully report all the characteristics which are actually available. Actually, it doesn't find the most important ones, the ones to subscribe to in order to get fast updating data, for example in an IMU. But I can find them using for example using this software: https://github.com/jnross/Bluetility/releases
I'm on MacOS 10.15.7 with Max 8.2.1

**Comment by mhamilt** [comment]
Note to Self:

[Bluetility](https://github.com/jnross/Bluetility) adds the advertisement data:

https://github.com/jnross/Bluetility/blob/ea374e8cfd760f1041259689bc70e5f43eec396f/Bluetility/Scanner.swift#L66

The object currently only reports discovered characteristics after connect

https://github.com/mhamilt/maxmsp-ble/blob/f45319cea52e397524d919e2e8c84b4a7d52618e/src/macos-ble/BleClasses/MacosBleCentral.m#L527-L576

And I think there may be some differences between what is reported

From the [CoreBluetooth Programming Guide](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/BestPracticesForInteractingWithARemotePeripheralDevice/BestPracticesForInteractingWithARemotePeripheralDevice.html#//apple_ref/doc/uid/TP40013257-CH6-SW10)

> A peripheral device may not be available to be connected to for a few reasons... In addition, some Bluetooth low energy devices use a random device address that changes periodically. Therefore, even if the device is nearby, the address of the device may have changed since the last time it was discovered by the system, in which case the CBPeripheral object you are trying to connect to doesn’t correspond to the actual peripheral device. If you cannot reconnect to the peripheral because its address has changed, you must rediscover it using the [scanForPeripheralsWithServices:options:](https://developer.apple.com/documentation/corebluetooth/cbcentralmanager/1518986-scanforperipheralswithservices) method
> For more information about random device addresses, see the Bluetooth 4.0 specification, Volume 3, Part C, Section 10.8 and [Bluetooth Accessory Design Guidelines for Apple Products.](https://developer.apple.com/hardwaredrivers/BluetoothDesignGuidelines.pdf)


Programatic reconnection to a device might not always succeed if CoreBluetooth decides to register the UUID differently.

I think this might be an unlikely situation. However to guard against it the better option is to connect to a device that is advertising a specific service UUID.

That service UUID needs to be known in the first instance, so correctly reporting advertisement data would help solve #21 as well.

**Comment by mhamilt** [comment]
I have perhaps found the origin of this

https://github.com/mhamilt/maxmsp-ble/blob/f45319cea52e397524d919e2e8c84b4a7d52618e/src/macos-ble/BleClasses/MacosBleCentral.m#L474-L478

Any Characteristic that can't be _Read_ is just ignored. At the time of making this I wasn't thinking too much about writing data to devices.

I can simply add in another couple of `else if` statements to try and parse out the useful info.

**Comment by mhamilt** [comment]
Reopening this until I update the release

**Comment by mhamilt** [comment]
This should now be sorted by ad188b3
