### ISSUE TITLE
Add extra outlet for onDevice connect

### ISSUE THREAD

**Issue by mhamilt** [mhamilt/maxmsp-ble#26]
Create an extra outlet that sends a message on device connect.

Message format something like

```
UUID ConnectTypeEnum
```

**Comment by josephlarralde** [comment]
Actually working on this, the 4th outlet is sending `connected <UUID>` messages.

I made a little progress and got rid of the double call to `didConnectPeripheral` issue by managing a connection state variable manually.
To achieve this, I added a `connectionState` property in `PeripheralConnectionManager` and I update it from `didConnectPeripheral`.
Not really happy with this workaround, as I guess there might be a better way to solve the problem as suggested in [this SO post](https://stackoverflow.com/questions/63252294/q-corebluetooth-peripheraldidconnect-called-twice), but I still can't figure out where this can originate from ... could it be that my 2 devices bear the exact same name ?

Will continue investigating.

**Comment by josephlarralde** [comment]
Oops, didn't notice this was closed, will give a try to alpha.8
Thanks !

**Comment by josephlarralde** [comment]
Perfect ! 👍

**Comment by josephlarralde** [comment]
Perfect ! 👍
