### ISSUE TITLE
Apple ARM architecture not currently supported?

### ISSUE THREAD

**Issue by ATRXIA** [mhamilt/maxmsp-ble#31]
Hi MHAMILT,
tried using the max-ble external on a MBP with M1pro ARM,
and I get the error " max-ble: could not load due to incorrect architecture "

I suppose it has to be updated and compiled for the ARM processor family ?
Thanks !
Gio

**Comment by ErmandoDulluku** [comment]
I am getting the same problem running M1.

**Comment by ATRXIA** [comment]
it works if you run Max via Rosetta :)

**Comment by ErmandoDulluku** [comment]
Thank you very much I did not know I could do that!

**Comment by mhamilt** [comment]
added a Universal build in the [latest release](https://github.com/mhamilt/maxmsp-ble/releases/tag/0.1.6). Though it would be good to confirm it functions on someone else's machine other than my own. I will leave this issue open until I am certain everything in the universal build functions as expected.
